export type ResultRecord = {
  candidate_id: string
  candidate_name: string
  position_id: string
  position_name: string
  votes: number
}

export function downloadResultsPdf(election: { id: string; name: string; description?: string | null; start_date: string; end_date: string }, results: ResultRecord[]) {
  try {
    // Group by position
    const byPosition = new Map<string, ResultRecord[]>()
    results.forEach(r => {
      if (!byPosition.has(r.position_id)) byPosition.set(r.position_id, [])
      byPosition.get(r.position_id)!.push(r)
    })

    // Build HTML
    const title = `${election.name} — Final Results`
    const start = new Date(election.start_date).toLocaleString('en-GB', { day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' })
    const end = new Date(election.end_date).toLocaleString('en-GB', { day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' })

    let sections = ''
    byPosition.forEach((records, positionId) => {
      const total = records.reduce((s, r) => s + r.votes, 0)
      const sorted = [...records].sort((a, b) => b.votes - a.votes)
      sections += `
        <div class="position">
          <h3>${sorted[0]?.position_name || 'Position'}</h3>
          <p class="muted">Total votes: ${total.toLocaleString()}</p>
          <table>
            <thead>
              <tr>
                <th style="text-align:left;">Candidate</th>
                <th style="text-align:right;">Votes</th>
                <th style="text-align:right;">Percent</th>
              </tr>
            </thead>
            <tbody>
              ${sorted.map(r => {
                const pct = total > 0 ? ((r.votes / total) * 100).toFixed(1) : '0.0'
                return `<tr>
                  <td>${r.candidate_name}</td>
                  <td style="text-align:right;">${r.votes.toLocaleString()}</td>
                  <td style="text-align:right;">${pct}%</td>
                </tr>`
              }).join('')}
            </tbody>
          </table>
        </div>
      `
    })

    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8" />
          <title>${title}</title>
          <style>
            * { box-sizing: border-box; }
            body { font-family: Arial, Helvetica, sans-serif; color: #111827; margin: 24px; }
            h1 { font-size: 20px; margin: 0 0 6px; }
            h2 { font-size: 16px; margin: 0 0 16px; color: #374151; }
            h3 { font-size: 14px; margin: 20px 0 6px; }
            .muted { color: #6B7280; font-size: 12px; }
            header { border-bottom: 1px solid #E5E7EB; padding-bottom: 12px; margin-bottom: 16px; }
            table { width: 100%; border-collapse: collapse; margin-top: 8px; }
            th, td { padding: 8px 10px; border-bottom: 1px solid #E5E7EB; font-size: 12px; }
            .position { page-break-inside: avoid; margin-bottom: 10px; }
            footer { margin-top: 24px; font-size: 11px; color: #6B7280; }
            @media print {
              @page { size: A4; margin: 16mm; }
              button { display: none; }
              body { margin: 0; }
            }
            .actions { margin: 16px 0; }
            .btn { padding: 8px 12px; border: 1px solid #D1D5DB; border-radius: 6px; background: white; cursor: pointer; }
          </style>
        </head>
        <body>
          <header>
            <h1>${title}</h1>
            <h2>${election.description ? election.description : ''}</h2>
            <p class="muted">Start: ${start} • End: ${end}</p>
          </header>
          <div class="actions">
            <button class="btn" onclick="window.print()">Download PDF</button>
          </div>
          ${sections}
          <footer>
            Generated by Prelyct Votes • ${new Date().toLocaleString('en-GB')}
          </footer>
          <script>
            // Auto-open print dialog after load (slight delay to ensure rendering)
            setTimeout(() => { window.print() }, 300);
          </script>
        </body>
      </html>
    `

    const win = window.open('', '_blank')
    if (!win) return
    win.document.open()
    win.document.write(html)
    win.document.close()
  } catch (error) {
    console.error('Failed to export results:', error)
    alert('Failed to prepare PDF. Please try again.')
  }
}



